### ISSUE TITLE
README.md needs to be update

### ISSUE THREAD

**Issue by jmostella** [Azure-Samples/openhack-devops-proctor#299]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Open README.md
### Any log messages given by the failure
>
N/A
### Expected/desired behavior
> * **leaderboard** - visualizes the uptime for the teams' APIs and contains an Azure Functions API which connects to CosmosDB, Sentinel (pods to query the APIs and report status), and a web front end. 

Directory seems to be missing in `master` branch.

> * **provision-proctor** - code to support the provisioning of a complete proctor environment (1 needed per event).

This seems to refer to the current directory.

> `tools`/`tripviewer` 

missing

### OS and Version?
N/A
### Versions
`master`

**Comment by DariuszPorowski** [comment]
issue expired - content has been changed
