### ISSUE TITLE
`provision-vm/deploy.sh` supplies parameter `dnsNameForPublicIP` to `azuredeploy.json`, which lacks this parameter. 

### ISSUE THREAD

**Issue by chgeuer** [Azure-Samples/openhack-devops-proctor#313]
https://github.com/Azure-Samples/openhack-devops-proctor/blob/db928374fec80adf1be8227c2c7d4bee71e37dc2/provision-vm/deploy.sh#L79

- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce

```bash
cd ./openhack-devops-proctor/provision-vm
./deploy.sh -l westeurope -n 1 -k "ssh-rsa AAAAB3NzaC1yc2EAAAA..."
```

### Any log messages given by the failure

```text
Deploying Proctor Virtual Machine...
unrecognized template parameter 'dnsNameForPublicIP'. Allowed parameters: ChatConnectionString, ChatMessageQueue, adminUsername, gitBranch, recipientEmail, spAppId, spPassword, spTenant, spUserName, sshKeyData, ubuntuOSVersion, vmSize
```

### Expected/desired behavior

Should pass the DNS name computed by `provision-vm/deploy.sh` down to `azuredeploy.json`.

### OS and Version?

> Linux (WSL)

**Comment by DariuszPorowski** [comment]
expired - content has been changed
