### ISSUE TITLE
need update for HTTP/2

### ISSUE THREAD

**Issue by davidgristwood** [Azure-Samples/openhack-devops-proctor#334]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

I have suggested fixed script for handling HTTP/2 responses:

healthcheck() {
    declare url=$1
    result=$(curl -i $url 2>/dev/null | grep HTTP/2) ******
    echo $result 
}

while [[ true ]]; do
   result=`healthcheck $endpoint` 
   declare status
   if [[ -z $result ]]; then 
      status="N/A"
   else
      status=${result:7:3} ******
   fi 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by larryclaman** [comment]
Any thoughts on this?  There are three open PRs fixing this problem: #322, #332, and #336.
Can you please review and accept one of them?

**Comment by larryclaman** [comment]
Can someone from the OH team **PLEASE** review this issue? There are now four different PRs that have been submitted with fixes to this problem.

**Comment by DariuszPorowski** [comment]
already fixed in https://github.com/Azure-Samples/openhack-devops-proctor/pull/343
