### ISSUE TITLE
Do you remove ~/.kube/conf ? 

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure-Samples/openhack-devops-proctor#58]
Question. 

When I deploy three teams, It success! However, I noticed that credential of kubernetes is removed. 
After deploy team 1. I use `az aks get-credential` command. However, after the team2, team3 deployment, it seems go away. 

Is it correct behavior?

**Comment by dtzar** [comment]
Yes, this is the designed behavior - all the credentials are going into their own files.  You should still be able to do a `kubectl config view` and see the other cluster contexts. @rguthriemsft

**Comment by TsuyoshiUshio** [comment]
Thanks!
