### ISSUE TITLE
proctor-vm requires sqlcmd

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure-Samples/openhack-devops-proctor#81]
When I deploy proctor-vm then team environment, I encounter an issue. 

```
$ `nohup ./setup.sh -i XXXXXXXXX -l eastus -n devopstsushi -e 2 `
nohup: ignoring input and redirecting stderr to stdout


Error: unknown command "/opt/mssql-tools/bin/sqlcmd" for "kubectl"
Run 'kubectl --help' for usage.
error: unknown command "/opt/mssql-tools/bin/sqlcmd" for "kubectl"
```

It might fix by this. 

```
    7  curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    8  curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
    9  sudo apt-get update
   10  sudo apt-get install mssql-tools unixodbc-dev
   11  echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
   12  source ~/.bashrc
```

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-linux-2017

**Comment by dcaro** [comment]
@odaibert can you have a look?

**Comment by TsuyoshiUshio** [comment]
Hi @dcaro , I found that there is sqlcmd installation for the proctor VM script. It might be caused by this point. 

https://github.com/Azure-Samples/openhack-devops-proctor/blob/9f8ff45c3806ad294a216f492580c3200378aaca/provision-team/deploy_ingress_dns.sh#L54

```
tiller=$(kubectl get pods --all-namespaces | grep tiller | awk '{print $4}')
```

My question is what do they intend to "awk '{print $4}' part.  There is no such thing like $4 parameter. 
the parameter is three.

**Comment by TsuyoshiUshio** [comment]
Hi @dcaro I try to reproduce however, I can't do that it works very well. 

Maybe the problem is, I use PowerShell on Linux for that try. This time, it behave weird, so I use Powershell for Windows. It works perfectly.
