### ISSUE TITLE
Provisioning Azure Functions error

### ISSUE THREAD

**Issue by odaibert** [Azure-Samples/openhack-devops-proctor#83]
When I try to deploy proctor-vm, I get this error: 

Provisioning Azure Functions (v2)...

installing newtonsoft.json
C:\projs\NEW\openhack-devops-proctor\provision-proctor\deploy.ps1 : A parameter cannot be found that matches parameter name 'functionName'.
At line:1 char:1
 .\deploy.ps1 -Location $YOUR_LOCATION -Number $YOUR_NUMBER -PublicKey ...
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [deploy.ps1], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,deploy.ps1

**Comment by TsuyoshiUshio** [comment]
As I said in the standup, it is the problem of the Readme. You can execute startup.sh instead.
